### ISSUE TITLE
Add HMS-400BM to documentation

### ISSUE THREAD

**Issue by tbnobody** [tbnobody/OpenDTU-docs#10]
See https://github.com/tbnobody/OpenDTU/issues/2170

**Comment by tbnobody** [comment]
Implemented in 1ad683a3589efca2513a841fb47bf3c29baa392f

**Comment by tt-why** [comment]
Are you sure prefix for HMS-400BM is only 1124 ?
Because mine is 1125 :pray: 
https://private-user-images.githubusercontent.com/62853285/352466009-c4447d3a-c4cb-4999-8aae-51f6966bf97b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODk4NDMsIm5iZiI6MTcyMzE4OTU0MywicGF0aCI6Ii82Mjg1MzI4NS8zNTI0NjYwMDktYzQ0NDdkM2EtYzRjYi00OTk5LThhYWUtNTFmNjk2NmJmOTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA3NDU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZWRlMThkYjI0MDFhNDhmOTgyYjA0ZmRiZmUxNzQ3YjY2YjA5ZjBiOTJjMjcxYWVkNzY3Y2IzY2JkZTQ0ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._EdvIhpvSN9RAPD0IAT7B0o8tEzg56Rxu2nLdQ35yoU
